apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: talos-ipv6-sanitizer-clusterrole
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "patch", "update"]
