apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: talos-ipv6-sanitizer-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: talos-ipv6-sanitizer-clusterrole
subjects:
  - kind: ServiceAccount
    name: talos-ipv6-sanitizer-sa
    namespace: default
