apiVersion: apps/v1
kind: Deployment
metadata:
  name: talos-ipv6-sanitizer-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: talos-ipv6-sanitizer
  template:
    metadata:
      labels:
        app: talos-ipv6-sanitizer
    spec:
      serviceAccountName: talos-ipv6-sanitizer-sa
      containers:
        - name: talos-ipv6-sanitizer
          # Altere aqui para o repositório/nome da imagem que você fizer push
          image: "seu-registro/talos-ipv6-sanitizer:latest"
          imagePullPolicy: Always
