apiVersion: apps/v1
kind: Deployment
metadata:
  name: teste-lb-deployment
  labels:
    app: teste-lb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teste-lb-app
  template:
    metadata:
      labels:
        app: teste-lb-app
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: teste-loadbalancer
  labels:
    app: teste-lb-app
  annotations:
    load-balancer.hetzner.cloud/location: "hel1"
    load-balancer.hetzner.cloud/network-zone: "eu-central"
    load-balancer.hetzner.cloud/name: "teste-loadbalancer"

    # Nome do certificado que você já criou no Hetzner Cloud
    load-balancer.hetzner.cloud/protocol: https
    load-balancer.hetzner.cloud/http-redirect-https: "true"
    load-balancer.hetzner.cloud/http-certificates: "cloud-iva-ai-applications-certificate"

    # Configurações de healthcheck
    load-balancer.hetzner.cloud/health-check-protocol: "http"
    load-balancer.hetzner.cloud/health-check-port: "80"
    load-balancer.hetzner.cloud/health-check--http-path: "/"
    load-balancer.hetzner.cloud/health-check-interval: "15s"
    load-balancer.hetzner.cloud/health-check-timeout: "10s"
    load-balancer.hetzner.cloud/health-check-retries: "3"

spec:
  type: LoadBalancer
  selector:
    app: teste-lb-app
  ports:
    # Porta 80 exposta externamente, redirecionada para containerPort 80
    - name: http
      port: 80
      targetPort: 80

    # Porta 443 exposta externamente, também redirecionada para containerPort 80
    - name: https
      port: 443
      targetPort: 80
