apiVersion: apps/v1
kind: Deployment
metadata:
  name: talos-ipv6-sanitizer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: talos-ipv6-sanitizer
  template:
    metadata:
      labels:
        app: talos-ipv6-sanitizer
    spec:
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          command: ["python", "/app/main.py"]
